import type { Metadata } from "next";
import "./globals.css";
import Navigator from "@/components/layouts/Navigator";
import DarkModeToggle from "@/components/utill/DarkModeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigator />
        {children}
        <DarkModeToggle />
      </body>
    </html>
  );
}
